### ISSUE TITLE
Gmsh error in gmsh verification tests. 

### ISSUE THREAD

**Issue by mihdicaballero** [xcfem/xc#102]
Hi! @lcpt I just run again the verification tests, and it almost was Ok in everything. I only had some errors with gmsh:

![image](https://user-images.githubusercontent.com/29404688/140214591-54aa486f-87ec-4144-879f-dfc9161b698d.png)

Thanks :)

_Originally posted by @mihdicaballero in https://github.com/xcfem/xc/issues/101#issuecomment-960251687_

**Comment by lcpt** [comment]
Hi, @mihdicaballero.

The problem was the slightly different meshes generated by different versions of GMSH. I've modified the test to check if the number of nodes and elements lie in a range instead of checking a particular value. The aim of the test is to verify that the interface with GMSH works fine, the details of the generated mesh are not important in this context.

You can pull the new tests from the repository.

**Comment by mihdicaballero** [comment]
Great! :D
